services:

  mysql:
    image: mysql:8.0
    container_name: ecommerce_mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: gateway_db
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init/mysql:/docker-entrypoint-initdb.d
    networks:
      - ecommerce
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot1234"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16-alpine
    container_name: ecommerce_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/postgres:/docker-entrypoint-initdb.d
    networks:
      - ecommerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7
    container_name: ecommerce_mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ecommerce

  gateway:
    build: ./Gateway
    container_name: ecommerce_gateway
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      APP_NAME: EcommerceGateway
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: http://localhost:8000
      APP_KEY: base64:gjnxzc6nsC8snucTeBF1pDpaVqaEbNVjOPLZiFvDBjI=
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: gateway_db
      DB_USERNAME: root
      DB_PASSWORD: root1234
      JWT_SECRET: Orgcgu8gYTgv64p8UvWOx1Npp9ntVLOh3HpT0cvxSceXg3OGVwilbqx9rM6SwQRU
      JWT_TTL: 60
      INTERNAL_KEY: EcommerceSecretKey
      USUARIOS_URL: http://usuarios:8001
      PRODUCTOS_URL: http://productos:8002
      ORDENES_URL: http://ordenes:8003
      PAGOS_URL: http://pagos:8004
      NOTIFICACIONES_URL: http://notificaciones:8005
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ecommerce

  usuarios:
    build: ./usuarios
    container_name: ecommerce_usuarios
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      DJANGO_SECRET_KEY: django-insecure-change-in-production
      DEBUG: "False"
      DB_NAME: usuarios_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      INTERNAL_KEY: EcommerceSecretKey
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ecommerce

  productos:
    build: ./productos
    container_name: ecommerce_productos
    restart: unless-stopped
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      DB_USER: root
      DB_PASSWORD: root1234
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: productos_db
      INTERNAL_KEY: EcommerceSecretKey
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ecommerce

  ordenes:
    build: ./ordenes
    container_name: ecommerce_ordenes
    restart: unless-stopped
    ports:
      - "8003:8003"
    environment:
      PORT: 8003
      MONGO_URI: mongodb://mongo:27017/ordenes_db
      INTERNAL_KEY: EcommerceSecretKey
    depends_on:
      - mongo
    networks:
      - ecommerce

  pagos:
    build: ./pagos
    container_name: ecommerce_pagos
    restart: unless-stopped
    ports:
      - "8004:8004"
    environment:
      APP_NAME: PagosService
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: base64:kHSkRl1imTtQ567PFiq3kbeKxXebZMA2TAVSZkeNEC0=
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: pagos_db
      DB_USERNAME: root
      DB_PASSWORD: root1234
      INTERNAL_KEY: EcommerceSecretKey
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ecommerce

  notificaciones:
    build: ./notificaciones
    container_name: ecommerce_notificaciones
    restart: unless-stopped
    ports:
      - "8005:8005"
    environment:
      PORT: 8005
      MONGO_URI: mongodb://mongo:27017/
      MONGO_DB: notificaciones_db
      INTERNAL_KEY: EcommerceSecretKey
    depends_on:
      - mongo
    networks:
      - ecommerce

networks:
  ecommerce:
    driver: bridge

volumes:
  mysql_data:
  postgres_data:
  mongo_data: